# Generated by Django 3.1.8 on 2021-04-21 16:17

import badgeprint.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Checkin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Event ID"
                    ),
                ),
                (
                    "attendee",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Attendee ID"
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="Checkin Time")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        default="local", max_length=30, verbose_name="Platform"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Code"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=badgeprint.models.user_directory_path,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "label_tpl",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Label Template",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Event Owner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="This Counter", max_length=60, verbose_name="Location"
                    ),
                ),
                ("uri", models.CharField(max_length=120, verbose_name="URI")),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("62x29", "DK-11209 (62x29)"),
                            ("62x100", "DK-11202 (62x100)"),
                        ],
                        default="62x29",
                        max_length=20,
                        verbose_name="Label",
                    ),
                ),
                ("debug", models.BooleanField(default=False, verbose_name="Debug")),
            ],
        ),
        migrations.CreateModel(
            name="PrinterUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Label"
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="badgeprint.printer",
                        verbose_name="Printer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=60, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Attending", max_length=10, verbose_name="Status"
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Ticket Type"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="badgeprint.event",
                        verbose_name="Event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Log Time"),
                ),
                (
                    "type",
                    models.CharField(
                        default="system", max_length=20, verbose_name="Type"
                    ),
                ),
                ("action", models.CharField(max_length=20, verbose_name="Action Name")),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="badgeprint.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="badgeprint.participant",
                        verbose_name="Participant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
